import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "./Problem.module.css";
import React, { useState, useEffect } from "react";
import { Header, Form, Container, Button, TextArea } from "semantic-ui-react";

type Problem = {
  id: number;
  title: string;
  text: string;
};

const Problem: NextPage = () => {
  const problem: Problem = {
    id: 2,
    title: "science",
    text: "すべての「物」は，<<<質量（重さ）>>>と<<<体積>>>をもっている。鉄などの固体は一定の形と体積があり，力を加えなければ変形しない。水などの液体は一定の体積をもつが一定の形はもたず，形はそれが入っている容器の形に従う。塩素などの気体は一定の体積と形をもたず，体積はそれが入っている容器の容積に，形はそれが入っている容器の形に従う。物を形や大きさなど外見に着目した場合，その物を<<<物体>>>という。例えば，コップといった場合，「液体が入れられる形」，「手でもてる程度の大きさ」といった外見があるので物体である。コップが割れるなどした場合，形・大きさはあるので物体ではあるがコップではなくなる（別の物体になる）。物をつくっている<<<材料>>>に着目した場合，その材料を<<<物質>>>という。",
  };
  const splitPattern = new RegExp(/<<<|>>>/, "i");
  const [isEdit, setIsEdit] = useState<boolean>(false);
  const [rawText, setRawText] = useState<string>(problem.text);
  const [contents, setContents] = useState<string[]>(
    rawText.split(splitPattern)
  );
  const [isCovered, setIsCovered] = useState<boolean>(true);
  const changeCoverState = () => {
    isCovered ? setIsCovered(false) : setIsCovered(true);
  };
  const cancelUpdateContent = () => {
    setRawText(problem.text);
    setIsEdit(false);
    setIsCovered(true)
  };
  const updateContent = () => {
    setContents(rawText.split(splitPattern));
    setIsEdit(false);
    setIsCovered(true)
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Red-Sheet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header as="h2" className={styles.title}>
          {problem.title}
        </Header>
        <div className={styles.content}>
          {isEdit ? (
            <>
              <Form className={styles.form}>
                <TextArea
                  autoHeight
                  value={rawText}
                  placeholder="Please enter a new problem."
                  onChange={(event) => {
                    setRawText(event.target.value);
                  }}
                  rows={3}
                  className={styles.formTextArea}
                />
              </Form>
            </>
          ) : (
            <>
              <Container className={styles.container}>
                {contents.map((content, index) =>
                  index % 2 == 0 ? (
                    content
                  ) : (
                    <span
                      className={styles.mark}
                      key={index}
                      style={
                        isCovered
                          ? { backgroundColor: "black" }
                          : { color: "red" }
                      }
                    >
                      {content}
                    </span>
                  )
                )}
              </Container>
            </>
          )}
        </div>
        <div className={styles.buttons}>
          {isEdit ? (
            <>
              <Button onClick={updateContent}>更新する</Button>
              <Button onClick={cancelUpdateContent}>変更取り消し</Button>
            </>
          ) : (
            <>
              <Button onClick={() => setIsEdit(true)}>
                テキストを変更する
              </Button>
              <Button onClick={changeCoverState}>
                覆いを{isCovered ? "外す" : "つける"}
              </Button>
            </>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Problem;
