import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "./Problem.module.css";
import React, { useState } from "react";
import { Header, Form, Container, Button } from "semantic-ui-react";

type Problem = {
  id: number;
  title: string;
  text: string;
};

const Problem: NextPage = () => {
  const problem: Problem = {
    id: 2,
    title: "science",
    text: "すべての「物」は，<<<質量（重さ）>>>と<<<体積>>>をもっている。鉄などの固体は一定の形と体積があり，力を加えなければ変形しない。水などの液体は一定の体積をもつが一定の形はもたず，形はそれが入っている容器の形に従う。塩素などの気体は一定の体積と形をもたず，体積はそれが入っている容器の容積に，形はそれが入っている容器の形に従う。物を形や大きさなど外見に着目した場合，その物を<<<物体>>>という。例えば，コップといった場合，「液体が入れられる形」，「手でもてる程度の大きさ」といった外見があるので物体である。コップが割れるなどした場合，形・大きさはあるので物体ではあるがコップではなくなる（別の物体になる）。物をつくっている<<<材料>>>に着目した場合，その材料を<<<物質>>>という。",
  };
  const [isEdit, setIsEdit] = useState<boolean>(false);
  const splitPattern = new RegExp(/<<<|>>>/, "i");
  return (
    <div className={styles.container}>
      <Head>
        <title>Red-Sheet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header as="h2" className={styles.title}>
          {problem.title}
        </Header>
        {isEdit ? (
          <>
            <Form className={styles.form}>
              <Form.TextArea
                autoHeight
                value={problem.text}
                placeholder="Enter your request message"
                rows={10}
                className={styles.formTextArea}
              />
            </Form>
            <Button onClick={() => setIsEdit(false)}>変更する</Button>
          </>
        ) : (
          <>
            <Container>
              {problem.text.split(splitPattern).map((fragment, index) =>
                index % 2 == 0 ? (
                  fragment
                ) : (
                  <span className={styles.mark} key={index / 2}>
                    {fragment}
                  </span>
                )
              )}
            </Container>
            <Button onClick={() => setIsEdit(true)}>変更する</Button>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Problem;
