import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "./Problems.module.css";
import React, { useEffect, useState } from "react";
import { Card, Icon } from "semantic-ui-react";
import getProblemsData from "../api/getProblemsData";
import { responseSymbol } from "next/dist/server/web/spec-compliant/fetch-event";
import Link from "next/link";
const postSendApi = "pages/api/addProblem";

type Problem = {
  id: number;
  title: string;
};

const getMessagesApi = "/api/getProblemsData";

const Problems: NextPage = () => {
  const [problems, setProblems] = useState<Problem[]>([]);

  useEffect(() => {
    (async () => {
      const response = await fetch(getMessagesApi);
      setProblems(await response.json());
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Red-Sheet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>問題一覧</div>
        <Card.Group className={styles.problems}>
          {problems.map((problem) => (
            <Link key={problem.id} href={`/problem/${problem.id}`}>
              <Card fluid as="a">
                <Card.Content>{problem.title}</Card.Content>
              </Card>
            </Link>
          ))}
            <Card fluid key={problems.length}>
              <Card.Content>
                <Icon name="plus" className={styles.plusIcon}/>
                追加する!
              </Card.Content>
            </Card>
        </Card.Group>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Problems;
